### ISSUE TITLE
How do I use baodata, also latest edits aren't fetched.

### ISSUE THREAD

**Issue by skaffen2** [maxmcd/gitbao#1]
Hi,  gitbao seems cool, thanks for sharing it.

I tried this, 

https://gist.github.com/skaffen2/edb43bd03e1f9517cac6

But my latest edits weren't used, I still got the same error message from the previous message.

New bao: edb43bd03e1f9517cac6
Fetching gist data
1 files found:
- main.go
  Downloading gist contents for build
  Files downloaded in directory: bao742830782
  Downloading Dependencies
  There was an error building this Go application:
  bao562855084/main.go:7:2: invalid import path: "https://github.com/maxmcd/baodata" package baodata: unrecognized import path "baodata" 
  error building

**Comment by maxmcd** [comment]
Thanks for checking out gtibao!

Looks like there was a bug pulling in the latest version of baodata when building. I cleared out the previous version and it seems to be working now. 

But yes, looks like it's having trouble pulling the latest edits, and running a working version of your code surfaced some weird issues with baodata id iteration. 

Here's the working version of your code I used. https://gist.github.com/maxmcd/01e4e554149bf2eab3a2

Closing this and opening up a few other issues for the mentioned bugs.
